version: '3'


vars:
  JSLIB_PATH: assets/js/lib
  TEMPL_VER: 'v0.3.920'
  ALPINEJS_VER: '3.13.7'

  PROD_DEST: '{{.ROOT_DIR}}/../zilllaiss.github.io'
  DEV_DEST: '{{.ROOT_DIR}}/dist'
  PROD: 'false'

tasks:
  build:all:
    desc: build all the project components.
    aliases:
      - b-all
    cmds:
      - task: deps
      - task: gen
      - task: build

  build:
    desc: build the project
    aliases:
      - b
    vars:
      DEST: '{{if eq .PROD "true"}}{{.PROD_DEST}}{{else}}{{.DEV_DEST}}{{end}}'
    cmds:
      - rm -rf {{.DEST}}/*
      - task: gen
      - sleep 1
      - go build -o bin/xyago 
      - FEST_SRC="{{.ROOT_DIR}}" FEST_DEST="{{.DEST}}" ./bin/xyago
      - prettier --write "{{.DEST}}/**/**.html"

  new:
    desc: initialize a new post
    requires:
      vars:
        - SLUG
    preconditions:
      - sh: '! test -f ./posts/{{.SLUG}}.md'
        msg: File already exists
    silent: true
    vars:
      TITLE: '{{.TITLE | default "Hello, world!"}}'
      FILEPATH: ./posts/{{.SLUG}}.md
      CURRENT_DATE:
        sh: date -I
      TEMPLATE: |
        ---
        title: {{.TITLE}}
        public: false
        published: {{.CURRENT_DATE}}
        updated: ''
        preamble: Hello, world!
        author: Zill_Laiss
        tags:
          - draft
        ---

        ## Draft
                
    cmds:
      - echo "{{.TEMPLATE}}" > {{.FILEPATH}}
      - echo '{{.FILEPATH}} is succesfully created.'

  run:
    cmds:
      - task: build:watch
      - ./bin/xyago

  init:
    aliases:
      - deps
    cmds:
      - task: deps:alpinejs
      - task: deps:templ
      - go mod tidy

  format:
    cmds:
     - prettier --write "{{.DEST_LOC}}/**/**.html"

  dev:
    watch: true
    cmds:
      - task: gen
      - sleep 1
      - task: run

  generate:
    aliases:
      - gen
    cmds:
      - task: gen:templ
      - task: gen:css

  commit:
    requires:
      vars:
        - MSG
    cmds:
      - git add .
      - git commit -m "{{.MSG}}"
      - task build PROD=true
      - | 
        git add .
        cd ../zilllaiss.github.io/
        git commit -m "{{.MSG}}"


##### INTERNAL ######
  

  deps:alpinejs:
    internal: true
    status:
      - test -f {{.JSLIB_PATH}}/alpine.js
      - '[[ $(cat .task/alpinejs_ver) == {{.ALPINEJS_VER}} ]]'
    cmds:
      - mkdir -p .task
      - echo "intalling alpinejs..."
      - curl https://unpkg.com/alpinejs@{{.ALPINEJS_VER}}/dist/cdn.min.js -o {{.JSLIB_PATH}}/alpine.js
      - 'echo {{.ALPINEJS_VER}} > .task/alpinejs_ver'
  
  deps:templ:
    internal: true
    status: 
      - go tool templ --version
      - '[[ $(templ version) == {{.TEMPL_VER}} ]]'
    cmds:
      - echo "installing templ..."
      - go get -tool github.com/a-h/templ/cmd/templ@{{.TEMPL_VER}} 
      - go get github.com/a-h/templ@{{.TEMPL_VER}}

  generate:templ:
    aliases:
      - gen:templ
    sources:
      - views/*.templ
    generates:
      - views/*_templ.go
    cmds:
      - go tool templ generate

  generate:css:
    aliases:
      - gen:css
    sources:
      - sass/*
    generates:
      - assets/styles/*
    cmds:
      - sass sass:assets/styles --update
