version: '3'

vars:
  JSLIB_PATH: assets/js/lib
  TEMPL_VER: 'v0.3.920'
  ALPINEJS_VER: '3.13.7'

  PROD_DEST: '{{.ROOT_DIR}}/../zilllaiss.github.io'
  PROD: 'false'

tasks:
  build:all:
    desc: build all the project components.
    aliases:
      - b-all
    cmds:
      - task: deps
      - task: gen
      - task: build

  build:
    desc: build the project
    aliases:
      - b
    cmds:
      - task: gen
      - go build -o bin/xyago 
      - FEST_SRC="{{.ROOT_DIR}}" FEST_DEST={{.ROOT_DIR}}/dist ./bin/xyago
      - |
        if [ '{{.PROD}}' == 'true' ] || [ '{{.PRETTY}}' == 'true' ]; then
          npx prettier --write --ignore-path '' "{{.ROOT_DIR}}/dist/**/**.html"
        fi
      - | 
        if [ '{{.PROD}}' == 'true' ]; then 
          rsync --archive --delete --exclude=.git '{{.ROOT_DIR}}/dist/' '{{.PROD_DEST}}'
        fi

  new:
    desc: initialize a new post
    requires:
      vars:
        - SLUG
    preconditions:
      - sh: '! test -f ./posts/{{.SLUG}}.md'
        msg: File already exists
    silent: true
    vars:
      TITLE: '{{.TITLE | default "Hello, world!"}}'
      FILEPATH: ./posts/{{.SLUG}}.md
      CURRENT_DATE:
        sh: date -I
      TEMPLATE: |
        ---
        title: {{.TITLE}}
        public: false
        published: {{.CURRENT_DATE}}
        updated: ''
        preamble: Hello, world!
        author: Zill_Laiss
        tags:
          - draft
        ---

        ## Draft
                
    cmds:
      - echo "{{.TEMPLATE}}" > {{.FILEPATH}}
      - echo '{{.FILEPATH}} is succesfully created.'

  run:
    cmds:
      - ./bin/xyago

  init:
    aliases:
      - deps
    cmds:
      - task: deps:alpinejs
      - task: deps:templ
      - npm i
      - go mod tidy

  dev:
    cmds:
      - |
        air &
        npx live-server --port=8080 dist

  live:
    cmd: npx live-server --port=8080 '{{.ROOT_DIR}}/dist'

  generate:
    aliases:
      - gen
    cmds:
      - task: gen:templ

  git:
    cmds:
      - git {{.CLI_ARGS}}
      - | 
        cd ../zilllaiss.github.io/ &&
        git {{.CLI_ARGS}}


##### INTERNAL ######
  

  deps:alpinejs:
    internal: true
    status:
      - test -f {{.JSLIB_PATH}}/alpine.js
      - '[[ $(cat .task/alpinejs_ver) == {{.ALPINEJS_VER}} ]]'
    cmds:
      - mkdir -p .task
      - echo "intalling alpinejs..."
      - curl https://unpkg.com/alpinejs@{{.ALPINEJS_VER}}/dist/cdn.min.js -o {{.JSLIB_PATH}}/alpine.js
      - 'echo {{.ALPINEJS_VER}} > .task/alpinejs_ver'
  
  deps:templ:
    internal: true
    status: 
      - go tool templ --version
      - '[[ $(templ version) == {{.TEMPL_VER}} ]]'
    cmds:
      - echo "installing templ..."
      - GOBIN="{{.ROOT_DIR}}/bin" go install github.com/a-h/templ/cmd/templ@{{.TEMPL_VER}} 
      - go get github.com/a-h/templ@{{.TEMPL_VER}}

  generate:templ:
    aliases:
      - gen:templ
    sources:
      - views/*.templ
    generates:
      - views/*_templ.go
    cmds:
      - ./bin/templ generate

