version: '3'


vars:
  JSLIB_PATH: assets/js/lib
  TEMPL_VER: 'v0.3.906'
  ALPINEJS_VER: '3.13.7'

  DEST_LOC: '{{.ROOT_DIR}}/../zilllaiss.github.io'
  PROD: 'false'

tasks:
  build:all:
    desc: build all the project components.
    aliases:
      - b-all
    cmds:
      - task: deps
      - task: gen
      - task: build

  build:
    cmds:
      - go build -o bin/xyago 
      - FEST_SRC="{{.ROOT_DIR}}" FEST_DEST="{{.DEST_LOC}}" ./bin/xyago

  build:watch:
    desc: development mode with hot-reload
    aliases:
      - b
    sources:
      - '*.go'
      - '**/**.go'
    generates:
      - bin/xyago
    cmds:
      - task: build

  build:prod:
    desc: build the project for production
    vars:
      PROD:
        'true'
    aliases:
      - bp
    cmds:
      - rm -rf {{.DEST_LOC}}/*
      - task: gen
      - sleep 1
      - go build -o bin/xyago 
      - FEST_SRC="{{.ROOT_DIR}}" FEST_DEST="{{.DEST_LOC}}" ./bin/xyago
      - prettier --write "{{.DEST_LOC}}/**/**.html"

  run:
    cmds:
      - task: build:watch
      - ./bin/xyago

  init:
    aliases:
      - deps
    cmds:
      - task: deps:alpinejs
      - task: deps:templ
      - go mod tidy

  format:
    cmds:
     - prettier --write "{{.DEST_LOC}}/**/**.html"

  dev:
    watch: true
    cmds:
      - task: gen
      - sleep 1
      - task: run

  generate:
    aliases:
      - gen
    cmds:
      - task: gen:templ
      - task: gen:css


##### INTERNAL ######
  

  deps:alpinejs:
    internal: true
    status:
      - test -f {{.JSLIB_PATH}}/alpine.js
      - '[[ $(cat .task/alpinejs_ver) == {{.ALPINEJS_VER}} ]]'
    cmds:
      - mkdir -p .task
      - echo "intalling alpinejs..."
      - curl https://unpkg.com/alpinejs@{{.ALPINEJS_VER}}/dist/cdn.min.js -o {{.JSLIB_PATH}}/alpine.js
      - 'echo {{.ALPINEJS_VER}} > .task/alpinejs_ver'
  
  deps:templ:
    internal: true
    status: 
      - command -v templ >> /dev/null
      - '[[ $(templ version) == {{.TEMPL_VER}} ]]'
    cmds:
      - echo "installing templ..."
      - go install github.com/a-h/templ/cmd/templ@{{.TEMPL_VER}} 
      - go get github.com/a-h/templ@{{.TEMPL_VER}}

  generate:templ:
    aliases:
      - gen:templ
    sources:
      - views/*.templ
    generates:
      - views/*_templ.go
    cmds:
      - templ generate

  generate:css:
    aliases:
      - gen:css
    sources:
      - sass/*
    generates:
      - assets/styles/*
    cmds:
      - sass sass:assets/styles --update
